# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taskwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 380)
        self.lineEditId = QtWidgets.QLineEdit(Dialog)
        self.lineEditId.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.lineEditId.setObjectName("lineEditId")
        self.lineEditNumber = QtWidgets.QLineEdit(Dialog)
        self.lineEditNumber.setGeometry(QtCore.QRect(150, 20, 241, 21))
        self.lineEditNumber.setObjectName("lineEditNumber")
        self.lineEditTheme = QtWidgets.QLineEdit(Dialog)
        self.lineEditTheme.setGeometry(QtCore.QRect(10, 50, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditTheme.setFont(font)
        self.lineEditTheme.setObjectName("lineEditTheme")
        self.lineEditDate = QtWidgets.QLineEdit(Dialog)
        self.lineEditDate.setGeometry(QtCore.QRect(10, 350, 261, 21))
        self.lineEditDate.setObjectName("lineEditDate")
        self.pushButtonSave = QtWidgets.QPushButton(Dialog)
        self.pushButtonSave.setGeometry(QtCore.QRect(320, 350, 70, 23))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 90, 381, 251))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonSave.setText(_translate("Dialog", "Save"))
